### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by MihaiStef69** [ayush7788/dwm#1]
Hi! The time is messed up.

**Comment by acidicneko** [comment]
What time is messed up? Please provide more details!

**Comment by MihaiStef69** [comment]
The shows is 5 hours behind. And do you know how to get back for my windows in tiling mode to open on the side? (yes i m a noob)

**Comment by MihaiStef69** [comment]
The clock shows*

**Comment by acidicneko** [comment]
Which time? On status bar?

**Comment by MihaiStef69** [comment]
yes

**Comment by acidicneko** [comment]
The time block isn't independent. It depends on your host's time. It runs `date` command to get time.
So check your host time.

**Comment by MihaiStef69** [comment]
thanks. And tha audio and mic don t work. But they work on xfce

**Comment by acidicneko** [comment]
Hey dude. This problem isn't related to this rice. It depends on you, that what tools you use to manage audio and mic.

**Comment by MihaiStef69** [comment]
ok
